In [1]:
import pandas as pd
from pathlib import Path
import time
import random
import requests
from urllib.parse import quote

In [2]:
output_folder = Path("../data/processed")

In [3]:


animals = pd.DataFrame({
    "animal": [
        "Giant panda",
        "Red panda",
        "Blue whale",
        "Bald eagle",
        "Komodo dragon"
    ],
    "page_title": [
        "Giant_panda",
        "Red_panda",
        "Blue_whale",
        "Bald_eagle",
        "Komodo_dragon"
    ],
    "animal_class": [
        "Mammal",
        "Mammal",
        "Mammal",
        "Bird",
        "Reptile"
    ]
})

data_folder = Path("../data/raw")
data_folder.mkdir(parents=True, exist_ok=True)

animals.to_csv(data_folder / "animals.csv", index = False)

animals

          animal     page_title animal_class
0    Giant panda    Giant_panda       Mammal
1      Red panda      Red_panda       Mammal
2     Blue whale     Blue_whale       Mammal
3     Bald eagle     Bald_eagle         Bird
4  Komodo dragon  Komodo_dragon      Reptile

In [4]:
# Getting the pageviews
DATA_DIR = Path("../data")
animals = pd.read_csv(DATA_DIR / "raw" / "animals.csv")

start_date = "20250101"
end_date = "20251231"

def get_pageviews(page_title, start, end):
    url = (
        "https://wikimedia.org/api/rest_v1/metrics/pageviews/"
        f"per-article/en.wikipedia.org/all-access/user/"
        f"{page_title}/daily/{start}/{end}"
    )

    response = requests.get(
        url,
        headers={"User-Agent": "wikipedia-animals-data-project/1.0"}
    )
    response.raise_for_status()

    records = response.json()["items"]

    return pd.DataFrame({
        "page_title": page_title,
        "date": [record["timestamp"][:8] for record in records],
        "pageviews": [record["views"] for record in records]
    })

In [5]:
animals["page_title"].iloc[2]
get_pageviews(animals["page_title"].iloc[2], start_date, str(int(start_date) + 5))

   page_title      date  pageviews
0  Blue_whale  20250101       2440
1  Blue_whale  20250102       2674
2  Blue_whale  20250103       2619
3  Blue_whale  20250104       3248
4  Blue_whale  20250105       3042
5  Blue_whale  20250106       2560

In [6]:
# All the pageviews across timefor the animals
results = []

for page_title in animals["page_title"]:
    animal_data = get_pageviews(
        page_title,
        start_date,
        end_date
    )

    results.append(animal_data)

pageviews_table = pd.concat(results, ignore_index=True)

pageviews_table

         page_title      date  pageviews
0       Giant_panda  20250101       2808
1       Giant_panda  20250102       2958
2       Giant_panda  20250103       2779
3       Giant_panda  20250104       2849
4       Giant_panda  20250105       2742
...             ...       ...        ...
1820  Komodo_dragon  20251227       2767
1821  Komodo_dragon  20251228       3046
1822  Komodo_dragon  20251229       2536
1823  Komodo_dragon  20251230       2701
1824  Komodo_dragon  20251231       5114

[1825 rows x 3 columns]

In [7]:
# With animal names and classes
pageviews_table = pageviews_table.merge(
    animals,
    on="page_title",
    how="left"
)
pageviews_table

         page_title      date  pageviews         animal animal_class
0       Giant_panda  20250101       2808    Giant panda       Mammal
1       Giant_panda  20250102       2958    Giant panda       Mammal
2       Giant_panda  20250103       2779    Giant panda       Mammal
3       Giant_panda  20250104       2849    Giant panda       Mammal
4       Giant_panda  20250105       2742    Giant panda       Mammal
...             ...       ...        ...            ...          ...
1820  Komodo_dragon  20251227       2767  Komodo dragon      Reptile
1821  Komodo_dragon  20251228       3046  Komodo dragon      Reptile
1822  Komodo_dragon  20251229       2536  Komodo dragon      Reptile
1823  Komodo_dragon  20251230       2701  Komodo dragon      Reptile
1824  Komodo_dragon  20251231       5114  Komodo dragon      Reptile

[1825 rows x 5 columns]

In [8]:
# The total pageviews
animal_totals = (
    pageviews_table
    .groupby(["animal", "page_title", "animal_class"], as_index=False)
    ["pageviews"]
    .sum()
    .rename(columns={"pageviews": "total_pageviews"})
    .sort_values("total_pageviews", ascending=False)
)

animal_totals

          animal     page_title animal_class  total_pageviews
2    Giant panda    Giant_panda       Mammal          1167395
3  Komodo dragon  Komodo_dragon      Reptile          1166332
1     Blue whale     Blue_whale       Mammal           922272
4      Red panda      Red_panda       Mammal           899850
0     Bald eagle     Bald_eagle         Bird           780893

In [9]:
# Totals by class
class_totals = (
    animal_totals
    .groupby(["animal_class"], as_index=False)
    ["total_pageviews"]
    .sum()
    .sort_values("total_pageviews", ascending=False)
)
class_totals

  animal_class  total_pageviews
1       Mammal          2989517
2      Reptile          1166332
0         Bird           780893

In [10]:
animals["page_title"].iloc[2]
get_pageviews(animals["page_title"].iloc[2], start_date, str(int(start_date) + 5))

   page_title      date  pageviews
0  Blue_whale  20250101       2440
1  Blue_whale  20250102       2674
2  Blue_whale  20250103       2619
3  Blue_whale  20250104       3248
4  Blue_whale  20250105       3042
5  Blue_whale  20250106       2560

In [11]:
# All the pageviews across timefor the animals
results = []

for page_title in animals["page_title"]:
    animal_data = get_pageviews(
        page_title,
        start_date,
        end_date
    )

    results.append(animal_data)

pageviews_table = pd.concat(results, ignore_index=True)

pageviews_table

         page_title      date  pageviews
0       Giant_panda  20250101       2808
1       Giant_panda  20250102       2958
2       Giant_panda  20250103       2779
3       Giant_panda  20250104       2849
4       Giant_panda  20250105       2742
...             ...       ...        ...
1820  Komodo_dragon  20251227       2767
1821  Komodo_dragon  20251228       3046
1822  Komodo_dragon  20251229       2536
1823  Komodo_dragon  20251230       2701
1824  Komodo_dragon  20251231       5114

[1825 rows x 3 columns]

In [12]:
# With animal names and classes
pageviews_table = pageviews_table.merge(
    animals,
    on="page_title",
    how="left"
)
pageviews_table

         page_title      date  pageviews         animal animal_class
0       Giant_panda  20250101       2808    Giant panda       Mammal
1       Giant_panda  20250102       2958    Giant panda       Mammal
2       Giant_panda  20250103       2779    Giant panda       Mammal
3       Giant_panda  20250104       2849    Giant panda       Mammal
4       Giant_panda  20250105       2742    Giant panda       Mammal
...             ...       ...        ...            ...          ...
1820  Komodo_dragon  20251227       2767  Komodo dragon      Reptile
1821  Komodo_dragon  20251228       3046  Komodo dragon      Reptile
1822  Komodo_dragon  20251229       2536  Komodo dragon      Reptile
1823  Komodo_dragon  20251230       2701  Komodo dragon      Reptile
1824  Komodo_dragon  20251231       5114  Komodo dragon      Reptile

[1825 rows x 5 columns]

In [13]:
# The total pageviews
animal_totals = (
    pageviews_table
    .groupby(["animal", "page_title", "animal_class"], as_index=False)
    ["pageviews"]
    .sum()
    .rename(columns={"pageviews": "total_pageviews"})
    .sort_values("total_pageviews", ascending=False)
)

animal_totals

          animal     page_title animal_class  total_pageviews
2    Giant panda    Giant_panda       Mammal          1167395
3  Komodo dragon  Komodo_dragon      Reptile          1166332
1     Blue whale     Blue_whale       Mammal           922272
4      Red panda      Red_panda       Mammal           899850
0     Bald eagle     Bald_eagle         Bird           780893

In [14]:
# Totals by class
class_totals = (
    animal_totals
    .groupby(["animal_class"], as_index=False)
    ["total_pageviews"]
    .sum()
    .sort_values("total_pageviews", ascending=False)
)
class_totals

  animal_class  total_pageviews
1       Mammal          2989517
2      Reptile          1166332
0         Bird           780893

In [15]:
# Now with the full animal table - mammals first

query = """
SELECT DISTINCT ?item ?page_title ?scientific_name WHERE {
  ?item wdt:P31 wd:Q16521;
        wdt:P105 wd:Q7432;
        wdt:P171* wd:Q7377.

  ?article schema:about ?item;
           schema:isPartOf <https://en.wikipedia.org/>;
           schema:name ?page_title.

  OPTIONAL {
    ?item wdt:P225 ?scientific_name.
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

response = requests.get(
    url,
    params={"query": query, "format": "json"},
    headers=headers
)

response.raise_for_status()
results = response.json()["results"]["bindings"]
mammals = pd.DataFrame([
    {
        "animal": row["page_title"]["value"],
        "page_title": row["page_title"]["value"].replace(" ", "_"),
        "animal_class": "Mammal"
    }
    for row in results
])
mammals

                           animal                     page_title animal_class
0           Eastern bent-wing bat          Eastern_bent-wing_bat       Mammal
1         Western bent-winged bat        Western_bent-winged_bat       Mammal
2           Small bent-winged bat          Small_bent-winged_bat       Mammal
3          Miniopterus sororculus         Miniopterus_sororculus       Mammal
4             Miniopterus newtoni            Miniopterus_newtoni       Mammal
..                            ...                            ...          ...
95  Greater short-nosed fruit bat  Greater_short-nosed_fruit_bat       Mammal
96                     Micronomus                     Micronomus       Mammal
97                Petra fruit bat                Petra_fruit_bat       Mammal
98            Vanikoro flying fox            Vanikoro_flying_fox       Mammal
99             Vanuatu flying fox             Vanuatu_flying_fox       Mammal

[100 rows x 3 columns]

In [16]:
# Reptiles

query = """
SELECT DISTINCT ?item ?page_title ?scientific_name WHERE {
  ?item wdt:P31 wd:Q16521;
        wdt:P105 wd:Q7432;
        wdt:P171* wd:Q10811.

  ?article schema:about ?item;
           schema:isPartOf <https://en.wikipedia.org/>;
           schema:name ?page_title.

  OPTIONAL {
    ?item wdt:P225 ?scientific_name.
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

response = requests.get(
    url,
    params={"query": query, "format": "json"},
    headers=headers
)

response.raise_for_status()
results = response.json()["results"]["bindings"]
reptiles = pd.DataFrame([
    {
        "animal": row["page_title"]["value"],
        "page_title": row["page_title"]["value"].replace(" ", "_"),
        "animal_class": "Reptile"
    }
    for row in results
])
reptiles

                   animal             page_title animal_class
0   Guarocuyus jaraguanus  Guarocuyus_jaraguanus      Reptile
1      Anomochilus weberi     Anomochilus_weberi      Reptile
2    Anomochilus leonardi   Anomochilus_leonardi      Reptile
3    Indian star tortoise   Indian_star_tortoise      Reptile
4   Burmese star tortoise  Burmese_star_tortoise      Reptile
..                    ...                    ...          ...
95         Texas tortoise         Texas_tortoise      Reptile
96  Anomochilus monticola  Anomochilus_monticola      Reptile
97      Common box turtle      Common_box_turtle      Reptile
98     Forsten's tortoise     Forsten's_tortoise      Reptile
99     Amboina box turtle     Amboina_box_turtle      Reptile

[100 rows x 3 columns]

In [17]:
# Fish - bony and cartiliginous classes combined here

query = """
SELECT DISTINCT ?item ?page_title ?scientific_name WHERE {
  VALUES ?fish_group {
    wd:Q127282
    wd:Q25371
  }

  ?item wdt:P31 wd:Q16521;
        wdt:P105 wd:Q7432;
        wdt:P171* ?fish_group.

  ?article schema:about ?item;
           schema:isPartOf <https://en.wikipedia.org/>;
           schema:name ?page_title.

  OPTIONAL {
    ?item wdt:P225 ?scientific_name.
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

response = requests.get(
    url,
    params={"query": query, "format": "json"},
    headers=headers
)

response.raise_for_status()
results = response.json()["results"]["bindings"]
fish = pd.DataFrame([
    {
        "animal": row["page_title"]["value"],
        "page_title": row["page_title"]["value"].replace(" ", "_"),
        "animal_class": "Fish"
    }
    for row in results
])
fish

                      animal                page_title animal_class
0              Betta edithae             Betta_edithae         Fish
1            Betta brownorum           Betta_brownorum         Fish
2           Betta channoides          Betta_channoides         Fish
3             Peaceful betta            Peaceful_betta         Fish
4                  John Dory                 John_Dory         Fish
..                       ...                       ...          ...
95       Barbeled houndshark       Barbeled_houndshark         Fish
96           European plaice           European_plaice         Fish
97  Beaufortia kweichowensis  Beaufortia_kweichowensis         Fish
98                Blue shark                Blue_shark         Fish
99                      Omul                      Omul         Fish

[100 rows x 3 columns]

In [18]:
# Birds

query = """
SELECT DISTINCT ?item ?page_title ?scientific_name WHERE {
  ?item wdt:P31 wd:Q16521;
        wdt:P105 wd:Q7432;
        wdt:P171+ wd:Q5113.

  ?article schema:about ?item;
           schema:isPartOf <https://en.wikipedia.org/>;
           schema:name ?page_title.

  OPTIONAL {
    ?item wdt:P225 ?scientific_name.
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

response = requests.get(
    url,
    params={"query": query, "format": "json"},
    headers=headers
)

response.raise_for_status()
results = response.json()["results"]["bindings"]
birds = pd.DataFrame([
    {
        "animal": row["page_title"]["value"],
        "page_title": row["page_title"]["value"].replace(" ", "_"),
        "animal_class": "Bird"
    }
    for row in results
])
birds

                         animal                   page_title animal_class
0                   Wild turkey                  Wild_turkey         Bird
1              Ocellated turkey             Ocellated_turkey         Bird
2     Green-crowned plovercrest    Green-crowned_plovercrest         Bird
3                  Banded quail                 Banded_quail         Bird
4    Southern giant hummingbird   Southern_giant_hummingbird         Bird
..                          ...                          ...          ...
95    Blue-throated mountaingem    Blue-throated_mountaingem         Bird
96        Razor-billed curassow        Razor-billed_curassow         Bird
97       Green-backed firecrown       Green-backed_firecrown         Bird
98  Emerald-chinned hummingbird  Emerald-chinned_hummingbird         Bird
99       Purple-bibbed whitetip       Purple-bibbed_whitetip         Bird

[100 rows x 3 columns]

In [19]:
# Amphibians

query = """
SELECT DISTINCT ?item ?page_title ?scientific_name WHERE {
  ?item wdt:P31 wd:Q16521;
        wdt:P105 wd:Q7432;
        wdt:P171+ wd:Q10908.

  ?article schema:about ?item;
           schema:isPartOf <https://en.wikipedia.org/>;
           schema:name ?page_title.

  OPTIONAL {
    ?item wdt:P225 ?scientific_name.
  }
}
LIMIT 100
"""

url = "https://query.wikidata.org/sparql"

headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

response = requests.get(
    url,
    params={"query": query, "format": "json"},
    headers=headers
)

response.raise_for_status()
results = response.json()["results"]["bindings"]
amphibians = pd.DataFrame([
    {
        "animal": row["page_title"]["value"],
        "page_title": row["page_title"]["value"].replace(" ", "_"),
        "animal_class": "Amphibian"
    }
    for row in results
])
amphibians

                         animal                   page_title animal_class
0           Marmorerpeton wakei          Marmorerpeton_wakei    Amphibian
1          Boulengerula taitana         Boulengerula_taitana    Amphibian
2              Caecilia volcani             Caecilia_volcani    Amphibian
3           Siphonops annulatus          Siphonops_annulatus    Amphibian
4             Stefania roraimae            Stefania_roraimae    Amphibian
..                          ...                          ...          ...
95  California giant salamander  California_giant_salamander    Amphibian
96     Coastal giant salamander     Coastal_giant_salamander    Amphibian
97          Red-crowned toadlet          Red-crowned_toadlet    Amphibian
98         Ptychadena boettgeri         Ptychadena_boettgeri    Amphibian
99         Leptobrachella aerea         Leptobrachella_aerea    Amphibian

[100 rows x 3 columns]

In [20]:
# New animals table
animals = pd.concat(
    [mammals, reptiles, birds, fish, amphibians], 
    ignore_index = True)
animals.to_csv(
    output_folder / "animals",
    index = False
)
animals

                          animal                   page_title animal_class
0          Eastern bent-wing bat        Eastern_bent-wing_bat       Mammal
1        Western bent-winged bat      Western_bent-winged_bat       Mammal
2          Small bent-winged bat        Small_bent-winged_bat       Mammal
3         Miniopterus sororculus       Miniopterus_sororculus       Mammal
4            Miniopterus newtoni          Miniopterus_newtoni       Mammal
..                           ...                          ...          ...
495  California giant salamander  California_giant_salamander    Amphibian
496     Coastal giant salamander     Coastal_giant_salamander    Amphibian
497          Red-crowned toadlet          Red-crowned_toadlet    Amphibian
498         Ptychadena boettgeri         Ptychadena_boettgeri    Amphibian
499         Leptobrachella aerea         Leptobrachella_aerea    Amphibian

[500 rows x 3 columns]

In [21]:
# Image count as a third variable

session = requests.Session()

image_headers = {
    "User-Agent": (
        "wikipedia-animals/1.0 "
        "(educational project; contact: noabm18@gmail.com)"
    )
}

def get_image_count(page_title, max_retries=8):
    url = "https://en.wikipedia.org/w/api.php"

    params = {
        "action": "query",
        "format": "json",
        "formatversion": 2,
        "prop": "images",
        "titles": page_title.replace("_", " "),
        "imlimit": "max"
    }

    image_count = 0

    while True:
        for attempt in range(max_retries):
            response = session.get(
                url,
                params=params,
                headers=image_headers,
                timeout=30
            )

            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After")

                if retry_after and retry_after.isdigit():
                    wait_time = int(retry_after)
                else:
                    wait_time = min(2 ** attempt, 120)

                wait_time += random.uniform(0, 1)

                print(
                    f"Rate limited on {page_title}. "
                    f"Waiting {wait_time:.1f} seconds."
                )

                time.sleep(wait_time)
                continue

            response.raise_for_status()
            break

        else:
            raise RuntimeError(
                f"Failed to retrieve {page_title} "
                f"after {max_retries} attempts"
            )

        data = response.json()
        page = data["query"]["pages"][0]
        
        image_count += len(page.get("images", []))

        if "continue" not in data:
            return image_count

        params.update(data["continue"])

        time.sleep(2)

In [22]:
get_image_count("bald_eagle")

43

In [23]:
image_results = []

for number, page_title in enumerate(
    animals["page_title"],
    start=1
):
    try:
        image_count = get_image_count(page_title)

        image_results.append({
            "page_title": page_title,
            "image_count": image_count
        })

        print(
            f"{number}/{len(animals)}: "
            f"{page_title} has {image_count} images"
        )

    except requests.RequestException as error:
        print(f"Skipped {page_title}: {error}")

    time.sleep(1)

1/500: Eastern_bent-wing_bat has 3 images
2/500: Western_bent-winged_bat has 4 images
3/500: Small_bent-winged_bat has 5 images
4/500: Miniopterus_sororculus has 3 images
5/500: Miniopterus_newtoni has 3 images
6/500: Manavi_long-fingered_bat has 5 images
7/500: Peterson's_long-fingered_bat has 5 images
8/500: Miniopterus_aelleni has 4 images
9/500: Common_bent-wing_bat has 6 images
10/500: Andean_caenolestid has 6 images
11/500: Gray-bellied_caenolestid has 8 images
12/500: Madagascan_flying_fox has 4 images
13/500: Seychelles_fruit_bat has 5 images
14/500: Aru_flying_fox has 4 images
15/500: Dusky_caenolestid has 9 images
16/500: Northern_caenolestid has 8 images
17/500: Long-haired_fruit_bat has 6 images
18/500: Franquet's_epauletted_fruit_bat has 5 images
19/500: Fijian_monkey-faced_bat has 4 images
20/500: Madagascar_sucker-footed_bat has 4 images
21/500: Madagascar_free-tailed_bat has 3 images
22/500: Greater_monkey-faced_bat has 3 images
23/500: African_sheath-tailed_bat has 5 images
24/500: Agricola's_gracile_opossum has 6 images
25/500: Southern_marsupial_mole has 7 images
26/500: Northern_marsupial_mole has 4 images
27/500: Horsfield's_fruit_bat has 4 images
28/500: Ashy_roundleaf_bat has 4 images
29/500: Dusky_leaf-nosed_bat has 4 images
30/500: Trident_bat has 4 images
31/500: Thailand_roundleaf_bat has 4 images
32/500: Lesser_great_leaf-nosed_bat has 4 images
33/500: Hispaniolan_greater_funnel-eared_bat has 4 images
34/500: Western_sucker-footed_bat has 4 images
35/500: Mexican_greater_funnel-eared_bat has 3 images
36/500: Jamaican_greater_funnel-eared_bat has 3 images
37/500: Mormopterus_francoismoutoui has 3 images
38/500: Small_white-winged_flying_fox has 4 images
39/500: Ashy-headed_flying_fox has 4 images
40/500: Black-eared_flying_fox has 5 images
41/500: Moluccan_flying_fox has 5 images
42/500: Bismarck_masked_flying_fox has 4 images
43/500: Makira_flying_fox has 4 images
44/500: Pemba_flying_fox has 4 images
45/500: Mauritian_flying_fox has 6 images
46/500: Noack's_roundleaf_bat has 4 images
47/500: Short-headed_roundleaf_bat has 5 images
48/500: Sorensen's_leaf-nosed_bat has 3 images
49/500: Malayan_roundleaf_bat has 4 images
50/500: Lesser_short-nosed_fruit_bat has 10 images
51/500: Western_rock_sengi has 5 images
52/500: Somali_sengi has 6 images
53/500: Swinhoe's_roundleaf_bat has 4 images
54/500: Gilliard's_flying_fox has 4 images
55/500: Lesser_flying_fox has 4 images
56/500: Benito_roundleaf_bat has 4 images
57/500: Hill's_roundleaf_bat has 3 images
58/500: Fly_River_roundleaf_bat has 4 images
59/500: Makira_roundleaf_bat has 3 images
60/500: Borneo_roundleaf_bat has 5 images
61/500: Pomona_roundleaf_bat has 3 images
62/500: Big-eared_roundleaf_bat has 5 images
63/500: Ridley's_leaf-nosed_bat has 4 images
64/500: Diadem_leaf-nosed_bat has 5 images
65/500: Philippine_forest_roundleaf_bat has 4 images
66/500: Indonesian_short-nosed_fruit_bat has 6 images
67/500: Dwarf_flying_fox has 6 images
68/500: Admiralty_flying_fox has 4 images
69/500: Ryukyu_flying_fox has 7 images
70/500: Sulawesi_stripe-faced_fruit_bat has 4 images
71/500: Ornate_flying_fox has 4 images
72/500: Small_flying_fox has 4 images
73/500: Big-eared_mastiff_bat has 4 images
74/500: Cuban_funnel-eared_bat has 3 images
75/500: Mantled_mastiff_bat has 4 images
76/500: Trinidadian_funnel-eared_bat has 4 images
77/500: Peale's_free-tailed_bat has 5 images
78/500: Seychelles_sheath-tailed_bat has 6 images
79/500: Large-eared_free-tailed_bat has 6 images
80/500: Broad-eared_bat has 6 images
81/500: Kalinowski's_mastiff_bat has 4 images
82/500: Javan_mastiff_bat has 4 images
83/500: Incan_little_mastiff_bat has 3 images
84/500: Peters's_wrinkle-lipped_bat has 4 images
85/500: Sumatran_mastiff_bat has 3 images
86/500: Rennell_flying_fox has 3 images
87/500: Bushveld_sengi has 5 images
88/500: Rufous_sengi has 5 images
89/500: Chilonatalus_macer has 3 images
90/500: Little_golden-mantled_flying_fox has 3 images
91/500: New_Zealand_lesser_short-tailed_bat has 9 images
92/500: Wood's_slit-faced_bat has 4 images
93/500: Philippine_gray_flying_fox has 5 images
94/500: Andersen's_flying_fox has 4 images
95/500: New_Zealand_greater_short-tailed_bat has 5 images
96/500: Greater_short-nosed_fruit_bat has 10 images
97/500: Micronomus has 3 images
98/500: Petra_fruit_bat has 0 images
99/500: Vanikoro_flying_fox has 4 images
100/500: Vanuatu_flying_fox has 5 images
101/500: Guarocuyus_jaraguanus has 0 images
102/500: Anomochilus_weberi has 5 images
103/500: Anomochilus_leonardi has 4 images
104/500: Indian_star_tortoise has 8 images
105/500: Burmese_star_tortoise has 4 images
106/500: Escambia_map_turtle has 6 images
107/500: Yunnan_box_turtle has 5 images
108/500: Texas_map_turtle has 6 images
109/500: Nubian_flapshell_turtle has 7 images
110/500: Alabama_map_turtle has 6 images
111/500: Olive_ridley_sea_turtle has 16 images
112/500: Florida_red-bellied_cooter has 6 images
113/500: Pearl_River_map_turtle has 6 images
114/500: Kemp's_ridley_sea_turtle has 18 images
115/500: Pan's_box_turtle has 5 images
116/500: McCord's_box_turtle has 7 images
117/500: Yellow-blotched_map_turtle has 6 images
118/500: Chersobius_signatus has 6 images
119/500: Bolson_tortoise has 7 images
120/500: Senegal_flapshell_turtle has 7 images
121/500: Chinese_box_turtle has 8 images
122/500: Oldham's_leaf_turtle has 7 images
123/500: Black_softshell_turtle has 10 images
124/500: Indian_softshell_turtle has 8 images
125/500: Yellow-footed_tortoise has 9 images
126/500: Amphisbaena_crisae has 2 images
127/500: Amphisbaena_cuiabana has 2 images
128/500: Amphisbaena_frontalis has 2 images
129/500: Amphisbaena_cunhai has 3 images
130/500: Amphisbaena_heterozonata has 0 images
131/500: Amphisbaena_hiata has 4 images
132/500: Amphisbaena_hastata has 2 images
133/500: Amphisbaena_ibijara has 0 images
134/500: Amphisbaena_ignatiana has 2 images
135/500: Barahona_amphisbaena has 4 images
136/500: Cuban_worm_lizard has 3 images
137/500: Darwin's_ringed_worm_lizard has 5 images
138/500: Cope's_worm_lizard has 3 images
139/500: Gonâve_worm_lizard has 3 images
140/500: Heath's_worm_lizard has 3 images
141/500: Hoge's_worm_lizard has 3 images
142/500: King's_worm_lizard has 5 images
143/500: Uncertain_worm_lizard has 2 images
144/500: Wood_turtle has 13 images
145/500: Yaqui_slider has 5 images
146/500: Maranhão_slider has 6 images
147/500: Indian_flapshell_turtle has 12 images
148/500: Hispaniolan_slider has 5 images
149/500: Cuatro_Ciénegas_slider has 6 images
150/500: Central_Antillean_slider has 7 images
151/500: Alabama_red-bellied_cooter has 9 images
152/500: Rio_Grande_cooter has 6 images
153/500: Spider_tortoise has 5 images
154/500: Bell's_hinge-back_tortoise has 5 images
155/500: Red-footed_tortoise has 16 images
156/500: Mexican_box_turtle has 10 images
157/500: Réunion_giant_tortoise has 6 images
158/500: Asian_narrow-headed_softshell_turtle has 5 images
159/500: Leith's_softshell_turtle has 6 images
160/500: Amphisbaena_caeca has 8 images
161/500: Amphisbaena_carli has 3 images
162/500: Amphisbaena_cegei has 3 images
163/500: Brazilian_worm_lizard has 2 images
164/500: Carvalho_worm_lizard has 3 images
165/500: Cayemite_long-tailed_amphisbaena has 3 images
166/500: Crooked_worm_lizard has 4 images
167/500: Cayemite_short-tailed_amphisbaena has 3 images
168/500: Cuban_pink_amphisbaena has 3 images
169/500: Leposternon_cerradensis has 2 images
170/500: Terrapene_ornata has 6 images
171/500: Hermann's_tortoise has 23 images
172/500: Spotted_box_turtle has 5 images
173/500: Burmese_narrow-headed_softshell_turtle has 4 images
174/500: Greek_tortoise has 14 images
175/500: Burmese_flapshell_turtle has 4 images
176/500: Indian_narrow-headed_softshell_turtle has 5 images
177/500: Marginated_tortoise has 25 images
178/500: Trachemys_callirostris has 4 images
179/500: Home's_hinge-back_tortoise has 5 images
180/500: Forest_hinge-back_tortoise has 10 images
181/500: Natal_hinge-back_tortoise has 6 images
182/500: Black-knobbed_map_turtle has 7 images
183/500: Vietnamese_pond_turtle has 5 images
184/500: Kleinmann's_tortoise has 13 images
185/500: Flat-backed_spider_tortoise has 5 images
186/500: Amphisbaena_arda has 2 images
187/500: Amphisbaena_bahiana has 2 images
188/500: Amphisbaena_bedai has 2 images
189/500: Amphisbaena_bilabialata has 3 images
190/500: Amphisbaena_brevis has 2 images
191/500: Amphisbaena_borelli has 4 images
192/500: Amphisbaena_bolivica has 3 images
193/500: Barbour's_worm_lizard has 2 images
194/500: Baker's_worm_lizard has 6 images
195/500: Cuban_many-ringed_amphisbaena has 3 images
196/500: Texas_tortoise has 12 images
197/500: Anomochilus_monticola has 5 images
198/500: Common_box_turtle has 13 images
199/500: Forsten's_tortoise has 6 images
200/500: Amboina_box_turtle has 10 images
201/500: Wild_turkey has 26 images
202/500: Ocellated_turkey has 11 images
203/500: Green-crowned_plovercrest has 5 images
204/500: Banded_quail has 8 images
205/500: Southern_giant_hummingbird has 12 images
206/500: Dwarf_tinamou has 8 images
207/500: Grey-bellied_comet has 10 images
208/500: Helmeted_guinea_fowl has 34 images
209/500: Southern_brown_kiwi has 11 images
210/500: Little_spotted_kiwi has 11 images
211/500: Great_spotted_kiwi has 13 images
212/500: North_Island_brown_kiwi has 12 images
213/500: Black_guan has 6 images
214/500: Talamanca_hummingbird has 11 images
215/500: Green-backed_hillstar has 6 images
216/500: Purple-crowned_plovercrest has 6 images
217/500: White-throated_daggerbill has 5 images
218/500: Marbled_wood_quail has 7 images
219/500: Brazilian_ruby has 7 images
220/500: Moluccan_megapode has 8 images
221/500: Antillean_crested_hummingbird has 17 images
222/500: Blue-chinned_sapphire has 4 images
223/500: Spix's_guan has 5 images
224/500: Stripe-faced_wood_quail has 5 images
225/500: Dark-backed_wood_quail has 6 images
226/500: Malleefowl has 17 images
227/500: White-browed_guan has 5 images
228/500: Crested_guan has 8 images
229/500: Andean_guan has 7 images
230/500: Horned_sungem has 19 images
231/500: Maleo has 8 images
232/500: Fiery-tailed_awlbill has 11 images
233/500: Slender-tailed_woodstar has 11 images
234/500: Blue-headed_hummingbird has 8 images
235/500: Black-fronted_piping_guan has 5 images
236/500: Mountain_velvetbreast has 14 images
237/500: Black-fronted_wood_quail has 5 images
238/500: White-crested_guan has 4 images
239/500: Rufous-fronted_wood_quail has 5 images
240/500: Red-faced_guan has 5 images
241/500: Cauca_guan has 5 images
242/500: Bearded_guan has 5 images
243/500: Dusky-legged_guan has 7 images
244/500: Red-billed_brushturkey has 3 images
245/500: Sparkling-tailed_woodstar has 12 images
246/500: Saw-billed_hermit has 12 images
247/500: Swallow-tailed_hummingbird has 9 images
248/500: Gorgeted_wood_quail has 6 images
249/500: Peruvian_sheartail has 14 images
250/500: Yungas_guan has 3 images
251/500: Versicolored_emerald has 5 images
252/500: White-throated_piping_guan has 4 images
253/500: Nahan's_partridge has 6 images
254/500: White-chested_emerald has 5 images
255/500: Black-eared_wood_quail has 6 images
256/500: Tawny-faced_quail has 10 images
257/500: Waigeo_brushturkey has 3 images
258/500: Stone_partridge has 3 images
259/500: Collared_brushturkey has 5 images
260/500: Black-breasted_wood_quail has 7 images
261/500: Fiery-throated_hummingbird has 14 images
262/500: Wattled_brushturkey has 9 images
263/500: Spotted_wood_quail has 6 images
264/500: Starred_wood_quail has 5 images
265/500: Singing_quail has 9 images
266/500: Black-billed_brushturkey has 5 images
267/500: Marail_guan has 5 images
268/500: Venezuelan_wood_quail has 5 images
269/500: Chestnut_wood_quail has 5 images
270/500: Rufous-breasted_wood_quail has 5 images
271/500: Rusty-margined_guan has 6 images
272/500: Baudo_guan has 5 images
273/500: Tacarcuna_wood_quail has 4 images
274/500: Blue-bearded_helmetcrest has 7 images
275/500: Buffy_helmetcrest has 5 images
276/500: White-bearded_helmetcrest has 6 images
277/500: Tolima_blossomcrown has 8 images
278/500: Rufous-gaped_hillstar has 4 images
279/500: Many-spotted_hummingbird has 13 images
280/500: Rivoli's_hummingbird has 12 images
281/500: Scissor-tailed_hummingbird has 11 images
282/500: Violet-headed_hummingbird has 12 images
283/500: Red-throated_piping_guan has 5 images
284/500: Green-bearded_helmetcrest has 6 images
285/500: Ferruginous_partridge has 7 images
286/500: Olivaceous_thornbill has 5 images
287/500: Green-tailed_emerald has 4 images
288/500: Chiribiquete_emerald has 4 images
289/500: Common_ostrich has 52 images
290/500: Rufous-vented_whitetip has 5 images
291/500: Western_capercaillie has 29 images
292/500: Red-tailed_comet has 16 images
293/500: Black_grouse has 18 images
294/500: Oasis_hummingbird has 12 images
295/500: Canivet's_emerald has 7 images
296/500: Blue-throated_mountaingem has 4 images
297/500: Razor-billed_curassow has 5 images
298/500: Green-backed_firecrown has 12 images
299/500: Emerald-chinned_hummingbird has 11 images
300/500: Purple-bibbed_whitetip has 9 images
301/500: Betta_edithae has 4 images
302/500: Betta_brownorum has 3 images
303/500: Betta_channoides has 4 images
304/500: Peaceful_betta has 6 images
305/500: John_Dory has 15 images
306/500: Siamese_fighting_fish has 16 images
307/500: Laetacara_curviceps has 3 images
308/500: Australian_grayling has 3 images
309/500: Murray_cod has 15 images
310/500: Nannacara_aureocephalus has 3 images
311/500: Oscar_(fish) has 12 images
312/500: Crenicichla_punctata has 3 images
313/500: Lugubria_johanna has 3 images
314/500: Striped_red_mullet has 16 images
315/500: Lugubria_strigata has 2 images
316/500: Lugubria_tigrina has 3 images
317/500: Zebra_acara has 5 images
318/500: Teleocichla_cinderella has 3 images
319/500: Pterophyllum_altum has 4 images
320/500: Convict_cichlid has 18 images
321/500: Australoheros_facetus has 4 images
322/500: Blue_acara has 4 images
323/500: Blue-eye_cichlid has 1 images
324/500: Mesonauta_festivus has 2 images
325/500: Mullus_barbatus has 8 images
326/500: Goldeneye_cichlid has 5 images
327/500: Green_terror has 5 images
328/500: Firemouth_cichlid has 6 images
329/500: Nannacara_bimaculata has 3 images
330/500: Jack_Dempsey_(fish) has 6 images
331/500: Parachromis_managuensis has 6 images
332/500: Rednose_labeo has 3 images
333/500: Silver_labeo has 5 images
334/500: Psednos_gelatinosus has 2 images
335/500: Psednos_anoderkes has 2 images
336/500: Psednos_harteli has 4 images
337/500: Psednos_micrurus has 4 images
338/500: Psednos_nataliae has 2 images
339/500: Lingcod has 18 images
340/500: Petenia_splendida has 5 images
341/500: Paraliparis_labiatus has 2 images
342/500: Paraliparis_eastmani has 2 images
343/500: Paraliparis_delphis has 2 images
344/500: Paraliparis_hobarti has 2 images
345/500: Paraliparis_incognita has 2 images
346/500: Paraliparis_kocki has 2 images
347/500: Paraliparis_impariporus has 2 images
348/500: Paraliparis_coracinus has 2 images
349/500: Paraliparis_dewitti has 2 images
350/500: Paraliparis_avellaneus has 2 images
351/500: Paraliparis_brunneocaudatus has 2 images
352/500: Paraliparis_costatus has 2 images
353/500: Paraliparis_lasti has 2 images
354/500: Paraliparis_infeliciter has 2 images
355/500: Paraliparis_brunneus has 2 images
356/500: Paraliparis_badius has 2 images
357/500: Pseudoplatystoma_magdaleniatum has 3 images
358/500: Pinirampus_pirinampu has 0 images
359/500: Zungaropsis has 2 images
360/500: Sorubim_lima has 7 images
361/500: Pinguipes_brasilianus has 2 images
362/500: Trixiphichthys_weberi has 0 images
363/500: Alburnoides_qanati has 3 images
364/500: Redhump_eartheater has 5 images
365/500: Psychrolutes_marcidus has 4 images
366/500: Mahi-mahi has 25 images
367/500: Stipecampus_cristatus has 4 images
368/500: Synchiropus_splendidus has 7 images
369/500: Paraliparis_bipolaris has 3 images
370/500: Paraliparis_gomoni has 2 images
371/500: Black_seasnail has 3 images
372/500: Paraliparis_carlbondi has 2 images
373/500: Pugnose_shiner has 4 images
374/500: Labeo_rosae has 4 images
375/500: Lemon_sole has 5 images
376/500: Red_cornetfish has 5 images
377/500: Pseudorhombus_arsius has 2 images
378/500: Alburnoides_eichwaldii has 4 images
379/500: Alburnoides_prespensis has 2 images
380/500: Javichthys_kailolae has 0 images
381/500: Transcaucasian_spirlin has 3 images
382/500: Pao_leiurus has 3 images
383/500: Mazarunia_mazarunii has 1 images
384/500: Satanoperca_lilith has 4 images
385/500: Aplochiton_taeniatus has 5 images
386/500: Aplochiton_zebra has 5 images
387/500: Razorbelly_scad has 6 images
388/500: European_eel has 15 images
389/500: Whitetip_weasel_shark has 5 images
390/500: Anarhichas_minor has 4 images
391/500: Australian_weasel_shark has 6 images
392/500: Sicklefin_weasel_shark has 8 images
393/500: Straight-tooth_weasel_shark has 5 images
394/500: Atlantic_weasel_shark has 6 images
395/500: Slender_weasel_shark has 6 images
396/500: Barbeled_houndshark has 5 images
397/500: European_plaice has 8 images
398/500: Beaufortia_kweichowensis has 3 images
399/500: Blue_shark has 19 images
400/500: Omul has 10 images
401/500: Marmorerpeton_wakei has 0 images
402/500: Boulengerula_taitana has 4 images
403/500: Caecilia_volcani has 2 images
404/500: Siphonops_annulatus has 6 images
405/500: Stefania_roraimae has 2 images
406/500: Italian_crested_newt has 7 images
407/500: Danube_crested_newt has 10 images
408/500: Boulengerula_niedeni has 3 images
409/500: Northern_crested_newt has 18 images
410/500: Two-toed_amphiuma has 6 images
411/500: Stefania_scalae has 3 images
412/500: Stefania_marahuaquensis has 3 images
413/500: Stefania_evansi has 4 images
414/500: Caecilia_crassisquama has 4 images
415/500: Amphiuma_pholeter has 5 images
416/500: Siphonops_hardyi has 3 images
417/500: Stefania_riae has 4 images
418/500: Alpine_salamander has 14 images
419/500: Hynobius_glacialis has 3 images
420/500: Fire_salamander has 19 images
421/500: Near_Eastern_fire_salamander has 6 images
422/500: Hynobius_nebulosus has 4 images
423/500: Hakuba_salamander has 3 images
424/500: Oita_salamander has 4 images
425/500: Hokuriku_salamander has 3 images
426/500: Oki_salamander has 3 images
427/500: Ptychadena_wadei has 4 images
428/500: Ptychadena_perreti has 3 images
429/500: Ptychadena_keilingi has 5 images
430/500: Ptychadena_filwoha has 0 images
431/500: Ptychadena_erlangeri has 4 images
432/500: Ptychadena_mapacha has 5 images
433/500: Ptychadena_subpunctata has 4 images
434/500: Ptychadena_oxyrhynchus has 5 images
435/500: Ptychadena_harenna has 4 images
436/500: Hylambates_keithae has 2 images
437/500: Siphonops_paulensis has 4 images
438/500: Siphonops_leucoderus has 4 images
439/500: Engystomops_randi has 3 images
440/500: Engystomops_coloradorum has 3 images
441/500: Engystomops_montubio has 4 images
442/500: Engystomops_pustulatus has 2 images
443/500: Hymenochirus_feae has 5 images
444/500: Hymenochirus_boettgeri has 3 images
445/500: Hymenochirus_boulengeri has 4 images
446/500: Uraeotyphlus_interruptus has 5 images
447/500: Uraeotyphlus_menoni has 5 images
448/500: Uraeotyphlus_malabaricus has 3 images
449/500: Uraeotyphlus_narayani has 7 images
450/500: Uraeotyphlus_oxyurus has 4 images
451/500: Leptobrachella_baluensis has 3 images
452/500: Leptobrachella_mjobergi has 3 images
453/500: Leptobrachella_parva has 3 images
454/500: Leptobrachella_natunae has 4 images
455/500: Leptobrachella_palmata has 2 images
456/500: Leptobrachella_brevicrus has 3 images
457/500: Leptobrachella_serasanae has 3 images
458/500: Hynobius_ikioi has 3 images
459/500: Liaoning_salamander has 0 images
460/500: Hynobius_fossigenus has 10 images
461/500: De_Witte's_snout-burrower has 4 images
462/500: Hynobius_quelpaertensis has 4 images
463/500: Pseudoeurycea_saltator has 4 images
464/500: Hynobius_shinichisatoi has 3 images
465/500: Hynobius_amakusaensis has 3 images
466/500: Hynobius_abuensis has 3 images
467/500: Hynobius_akiensis has 2 images

In [24]:
image_table = pd.DataFrame(image_results)

image_table

                      page_title  image_count
0          Eastern_bent-wing_bat            3
1        Western_bent-winged_bat            4
2          Small_bent-winged_bat            5
3         Miniopterus_sororculus            3
4            Miniopterus_newtoni            3
..                           ...          ...
495  California_giant_salamander            8
496     Coastal_giant_salamander            4
497          Red-crowned_toadlet            5
498         Ptychadena_boettgeri            3
499         Leptobrachella_aerea            2

[500 rows x 2 columns]

In [25]:
# A new get_pageviews because it easily gets timeout errors for this many queries

session = requests.Session()

pageview_headers = {
    "User-Agent": "wikipedia-animals/1.0 (educational data science project)"
}

def get_pageviews(page_title, start, end, max_retries=6):
    encoded_title = quote(
        page_title.replace(" ", "_"),
        safe=""
    )

    url = (
        "https://wikimedia.org/api/rest_v1/metrics/pageviews/"
        f"per-article/en.wikipedia.org/all-access/user/"
        f"{encoded_title}/daily/{start}/{end}"
    )

    for attempt in range(max_retries):
        response = session.get(
            url,
            headers=pageview_headers,
            timeout=30
        )

        if response.status_code == 429:
            retry_after = response.headers.get("Retry-After")

            if retry_after and retry_after.isdigit():
                wait_time = int(retry_after)
            else:
                wait_time = 2 ** attempt

            print(
                f"Rate limited on {page_title}. "
                f"Waiting {wait_time} seconds."
            )

            time.sleep(wait_time)
            continue

        response.raise_for_status()

        records = response.json()["items"]

        return pd.DataFrame({
            "page_title": page_title,
            "date": [
                record["timestamp"][:8]
                for record in records
            ],
            "pageviews": [
                record["views"]
                for record in records
            ]
        })

    raise RuntimeError(
        f"Could not retrieve {page_title} after {max_retries} attempts"
    )

In [26]:
# All the pageviews across timefor the animals - now with the full table

pageview_results = []

for number, page_title in enumerate(
    animals["page_title"],
    start=1
):
    try:
        animal_data = get_pageviews(
            page_title,
            start_date,
            end_date
        )

        pageview_results.append(animal_data)

        print(
            f"{number}/{len(animals)}: "
            f"downloaded {page_title}"
        )

    except requests.RequestException as error:
        print(f"Skipped {page_title}: {error}")

    except RuntimeError as error:
        print(error)

    time.sleep(1)

1/500: downloaded Eastern_bent-wing_bat
2/500: downloaded Western_bent-winged_bat
3/500: downloaded Small_bent-winged_bat
4/500: downloaded Miniopterus_sororculus
5/500: downloaded Miniopterus_newtoni
6/500: downloaded Manavi_long-fingered_bat
7/500: downloaded Peterson's_long-fingered_bat
8/500: downloaded Miniopterus_aelleni
9/500: downloaded Common_bent-wing_bat
10/500: downloaded Andean_caenolestid
Rate limited on Gray-bellied_caenolestid. Waiting 23 seconds.
11/500: downloaded Gray-bellied_caenolestid
12/500: downloaded Madagascan_flying_fox
13/500: downloaded Seychelles_fruit_bat
14/500: downloaded Aru_flying_fox
15/500: downloaded Dusky_caenolestid
16/500: downloaded Northern_caenolestid
17/500: downloaded Long-haired_fruit_bat
18/500: downloaded Franquet's_epauletted_fruit_bat
19/500: downloaded Fijian_monkey-faced_bat
20/500: downloaded Madagascar_sucker-footed_bat
Rate limited on Madagascar_free-tailed_bat. Waiting 49 seconds.
21/500: downloaded Madagascar_free-tailed_bat
22/500: downloaded Greater_monkey-faced_bat
23/500: downloaded African_sheath-tailed_bat
24/500: downloaded Agricola's_gracile_opossum
25/500: downloaded Southern_marsupial_mole
26/500: downloaded Northern_marsupial_mole
27/500: downloaded Horsfield's_fruit_bat
28/500: downloaded Ashy_roundleaf_bat
29/500: downloaded Dusky_leaf-nosed_bat
30/500: downloaded Trident_bat
Rate limited on Thailand_roundleaf_bat. Waiting 49 seconds.
31/500: downloaded Thailand_roundleaf_bat
32/500: downloaded Lesser_great_leaf-nosed_bat
33/500: downloaded Hispaniolan_greater_funnel-eared_bat
34/500: downloaded Western_sucker-footed_bat
35/500: downloaded Mexican_greater_funnel-eared_bat
36/500: downloaded Jamaican_greater_funnel-eared_bat
37/500: downloaded Mormopterus_francoismoutoui
38/500: downloaded Small_white-winged_flying_fox
39/500: downloaded Ashy-headed_flying_fox
40/500: downloaded Black-eared_flying_fox
Rate limited on Moluccan_flying_fox. Waiting 50 seconds.
41/500: downloaded Moluccan_flying_fox
42/500: downloaded Bismarck_masked_flying_fox
43/500: downloaded Makira_flying_fox
44/500: downloaded Pemba_flying_fox
45/500: downloaded Mauritian_flying_fox
46/500: downloaded Noack's_roundleaf_bat
47/500: downloaded Short-headed_roundleaf_bat
48/500: downloaded Sorensen's_leaf-nosed_bat
49/500: downloaded Malayan_roundleaf_bat
50/500: downloaded Lesser_short-nosed_fruit_bat
Rate limited on Western_rock_sengi. Waiting 49 seconds.
Skipped Western_rock_sengi: 404 Client Error: Not Found for url: https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Western_rock_sengi/daily/20250101/20251231
52/500: downloaded Somali_sengi
Skipped Swinhoe's_roundleaf_bat: 404 Client Error: Not Found for url: https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Swinhoe%27s_roundleaf_bat/daily/20250101/20251231
54/500: downloaded Gilliard's_flying_fox
55/500: downloaded Lesser_flying_fox
56/500: downloaded Benito_roundleaf_bat
57/500: downloaded Hill's_roundleaf_bat
58/500: downloaded Fly_River_roundleaf_bat
59/500: downloaded Makira_roundleaf_bat
60/500: downloaded Borneo_roundleaf_bat
Rate limited on Pomona_roundleaf_bat. Waiting 49 seconds.
61/500: downloaded Pomona_roundleaf_bat
62/500: downloaded Big-eared_roundleaf_bat
63/500: downloaded Ridley's_leaf-nosed_bat
64/500: downloaded Diadem_leaf-nosed_bat
65/500: downloaded Philippine_forest_roundleaf_bat
66/500: downloaded Indonesian_short-nosed_fruit_bat
67/500: downloaded Dwarf_flying_fox
68/500: downloaded Admiralty_flying_fox
69/500: downloaded Ryukyu_flying_fox
70/500: downloaded Sulawesi_stripe-faced_fruit_bat
Rate limited on Ornate_flying_fox. Waiting 49 seconds.
71/500: downloaded Ornate_flying_fox
72/500: downloaded Small_flying_fox
73/500: downloaded Big-eared_mastiff_bat
74/500: downloaded Cuban_funnel-eared_bat
75/500: downloaded Mantled_mastiff_bat
76/500: downloaded Trinidadian_funnel-eared_bat
77/500: downloaded Peale's_free-tailed_bat
78/500: downloaded Seychelles_sheath-tailed_bat
79/500: downloaded Large-eared_free-tailed_bat
80/500: downloaded Broad-eared_bat
Rate limited on Kalinowski's_mastiff_bat. Waiting 49 seconds.
81/500: downloaded Kalinowski's_mastiff_bat
82/500: downloaded Javan_mastiff_bat
83/500: downloaded Incan_little_mastiff_bat
84/500: downloaded Peters's_wrinkle-lipped_bat
85/500: downloaded Sumatran_mastiff_bat
86/500: downloaded Rennell_flying_fox
Skipped Bushveld_sengi: 404 Client Error: Not Found for url: https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Bushveld_sengi/daily/20250101/20251231
Skipped Rufous_sengi: 404 Client Error: Not Found for url: https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Rufous_sengi/daily/20250101/20251231
89/500: downloaded Chilonatalus_macer
90/500: downloaded Little_golden-mantled_flying_fox
Rate limited on New_Zealand_lesser_short-tailed_bat. Waiting 49 seconds.
91/500: downloaded New_Zealand_lesser_short-tailed_bat
92/500: downloaded Wood's_slit-faced_bat
93/500: downloaded Philippine_gray_flying_fox
94/500: downloaded Andersen's_flying_fox
95/500: downloaded New_Zealand_greater_short-tailed_bat
96/500: downloaded Greater_short-nosed_fruit_bat
97/500: downloaded Micronomus
98/500: downloaded Petra_fruit_bat
99/500: downloaded Vanikoro_flying_fox
100/500: downloaded Vanuatu_flying_fox
Rate limited on Guarocuyus_jaraguanus. Waiting 49 seconds.
101/500: downloaded Guarocuyus_jaraguanus
102/500: downloaded Anomochilus_weberi
103/500: downloaded Anomochilus_leonardi
104/500: downloaded Indian_star_tortoise
105/500: downloaded Burmese_star_tortoise
106/500: downloaded Escambia_map_turtle
107/500: downloaded Yunnan_box_turtle
108/500: downloaded Texas_map_turtle
109/500: downloaded Nubian_flapshell_turtle
110/500: downloaded Alabama_map_turtle
Rate limited on Olive_ridley_sea_turtle. Waiting 49 seconds.
111/500: downloaded Olive_ridley_sea_turtle
112/500: downloaded Florida_red-bellied_cooter
113/500: downloaded Pearl_River_map_turtle
114/500: downloaded Kemp's_ridley_sea_turtle
115/500: downloaded Pan's_box_turtle
116/500: downloaded McCord's_box_turtle
117/500: downloaded Yellow-blotched_map_turtle
118/500: downloaded Chersobius_signatus
119/500: downloaded Bolson_tortoise
120/500: downloaded Senegal_flapshell_turtle
Rate limited on Chinese_box_turtle. Waiting 50 seconds.
121/500: downloaded Chinese_box_turtle
122/500: downloaded Oldham's_leaf_turtle
123/500: downloaded Black_softshell_turtle
124/500: downloaded Indian_softshell_turtle
125/500: downloaded Yellow-footed_tortoise
126/500: downloaded Amphisbaena_crisae
127/500: downloaded Amphisbaena_cuiabana
128/500: downloaded Amphisbaena_frontalis
129/500: downloaded Amphisbaena_cunhai
130/500: downloaded Amphisbaena_heterozonata
Rate limited on Amphisbaena_hiata. Waiting 48 seconds.
131/500: downloaded Amphisbaena_hiata
132/500: downloaded Amphisbaena_hastata
133/500: downloaded Amphisbaena_ibijara
134/500: downloaded Amphisbaena_ignatiana
135/500: downloaded Barahona_amphisbaena
136/500: downloaded Cuban_worm_lizard
137/500: downloaded Darwin's_ringed_worm_lizard
138/500: downloaded Cope's_worm_lizard
139/500: downloaded Gonâve_worm_lizard
140/500: downloaded Heath's_worm_lizard
Rate limited on Hoge's_worm_lizard. Waiting 49 seconds.
141/500: downloaded Hoge's_worm_lizard
142/500: downloaded King's_worm_lizard
143/500: downloaded Uncertain_worm_lizard
144/500: downloaded Wood_turtle
145/500: downloaded Yaqui_slider
146/500: downloaded Maranhão_slider
147/500: downloaded Indian_flapshell_turtle
148/500: downloaded Hispaniolan_slider
149/500: downloaded Cuatro_Ciénegas_slider
150/500: downloaded Central_Antillean_slider
Rate limited on Alabama_red-bellied_cooter. Waiting 49 seconds.
151/500: downloaded Alabama_red-bellied_cooter
152/500: downloaded Rio_Grande_cooter
153/500: downloaded Spider_tortoise
154/500: downloaded Bell's_hinge-back_tortoise
155/500: downloaded Red-footed_tortoise
156/500: downloaded Mexican_box_turtle
157/500: downloaded Réunion_giant_tortoise
158/500: downloaded Asian_narrow-headed_softshell_turtle
159/500: downloaded Leith's_softshell_turtle
160/500: downloaded Amphisbaena_caeca
Rate limited on Amphisbaena_carli. Waiting 49 seconds.
161/500: downloaded Amphisbaena_carli
162/500: downloaded Amphisbaena_cegei
163/500: downloaded Brazilian_worm_lizard
164/500: downloaded Carvalho_worm_lizard
165/500: downloaded Cayemite_long-tailed_amphisbaena
166/500: downloaded Crooked_worm_lizard
167/500: downloaded Cayemite_short-tailed_amphisbaena
168/500: downloaded Cuban_pink_amphisbaena
169/500: downloaded Leposternon_cerradensis
170/500: downloaded Terrapene_ornata
Rate limited on Hermann's_tortoise. Waiting 49 seconds.
171/500: downloaded Hermann's_tortoise
172/500: downloaded Spotted_box_turtle
173/500: downloaded Burmese_narrow-headed_softshell_turtle
174/500: downloaded Greek_tortoise
175/500: downloaded Burmese_flapshell_turtle
176/500: downloaded Indian_narrow-headed_softshell_turtle
177/500: downloaded Marginated_tortoise
178/500: downloaded Trachemys_callirostris
179/500: downloaded Home's_hinge-back_tortoise
180/500: downloaded Forest_hinge-back_tortoise
Rate limited on Natal_hinge-back_tortoise. Waiting 50 seconds.
181/500: downloaded Natal_hinge-back_tortoise
182/500: downloaded Black-knobbed_map_turtle
183/500: downloaded Vietnamese_pond_turtle
184/500: downloaded Kleinmann's_tortoise
185/500: downloaded Flat-backed_spider_tortoise
186/500: downloaded Amphisbaena_arda
187/500: downloaded Amphisbaena_bahiana
188/500: downloaded Amphisbaena_bedai
189/500: downloaded Amphisbaena_bilabialata
190/500: downloaded Amphisbaena_brevis
Rate limited on Amphisbaena_borelli. Waiting 49 seconds.
191/500: downloaded Amphisbaena_borelli
192/500: downloaded Amphisbaena_bolivica
193/500: downloaded Barbour's_worm_lizard
194/500: downloaded Baker's_worm_lizard
195/500: downloaded Cuban_many-ringed_amphisbaena
196/500: downloaded Texas_tortoise
197/500: downloaded Anomochilus_monticola
198/500: downloaded Common_box_turtle
199/500: downloaded Forsten's_tortoise
200/500: downloaded Amboina_box_turtle
Rate limited on Wild_turkey. Waiting 49 seconds.
201/500: downloaded Wild_turkey
202/500: downloaded Ocellated_turkey
203/500: downloaded Green-crowned_plovercrest
204/500: downloaded Banded_quail
205/500: downloaded Southern_giant_hummingbird
206/500: downloaded Dwarf_tinamou
207/500: downloaded Grey-bellied_comet
208/500: downloaded Helmeted_guinea_fowl
209/500: downloaded Southern_brown_kiwi
210/500: downloaded Little_spotted_kiwi
Rate limited on Great_spotted_kiwi. Waiting 49 seconds.
211/500: downloaded Great_spotted_kiwi
212/500: downloaded North_Island_brown_kiwi
213/500: downloaded Black_guan
214/500: downloaded Talamanca_hummingbird
215/500: downloaded Green-backed_hillstar
216/500: downloaded Purple-crowned_plovercrest
217/500: downloaded White-throated_daggerbill
218/500: downloaded Marbled_wood_quail
219/500: downloaded Brazilian_ruby
220/500: downloaded Moluccan_megapode
Rate limited on Antillean_crested_hummingbird. Waiting 49 seconds.
221/500: downloaded Antillean_crested_hummingbird
222/500: downloaded Blue-chinned_sapphire
223/500: downloaded Spix's_guan
224/500: downloaded Stripe-faced_wood_quail
225/500: downloaded Dark-backed_wood_quail
226/500: downloaded Malleefowl
227/500: downloaded White-browed_guan
228/500: downloaded Crested_guan
229/500: downloaded Andean_guan
230/500: downloaded Horned_sungem
Rate limited on Maleo. Waiting 49 seconds.
231/500: downloaded Maleo
232/500: downloaded Fiery-tailed_awlbill
233/500: downloaded Slender-tailed_woodstar
234/500: downloaded Blue-headed_hummingbird
235/500: downloaded Black-fronted_piping_guan
236/500: downloaded Mountain_velvetbreast
237/500: downloaded Black-fronted_wood_quail
238/500: downloaded White-crested_guan
239/500: downloaded Rufous-fronted_wood_quail
240/500: downloaded Red-faced_guan
Rate limited on Cauca_guan. Waiting 49 seconds.
241/500: downloaded Cauca_guan
242/500: downloaded Bearded_guan
243/500: downloaded Dusky-legged_guan
244/500: downloaded Red-billed_brushturkey
245/500: downloaded Sparkling-tailed_woodstar
246/500: downloaded Saw-billed_hermit
247/500: downloaded Swallow-tailed_hummingbird
248/500: downloaded Gorgeted_wood_quail
249/500: downloaded Peruvian_sheartail
250/500: downloaded Yungas_guan
Rate limited on Versicolored_emerald. Waiting 49 seconds.
251/500: downloaded Versicolored_emerald
252/500: downloaded White-throated_piping_guan
253/500: downloaded Nahan's_partridge
254/500: downloaded White-chested_emerald
255/500: downloaded Black-eared_wood_quail
256/500: downloaded Tawny-faced_quail
257/500: downloaded Waigeo_brushturkey
258/500: downloaded Stone_partridge
259/500: downloaded Collared_brushturkey
260/500: downloaded Black-breasted_wood_quail
Rate limited on Fiery-throated_hummingbird. Waiting 49 seconds.
261/500: downloaded Fiery-throated_hummingbird
262/500: downloaded Wattled_brushturkey
263/500: downloaded Spotted_wood_quail
264/500: downloaded Starred_wood_quail
265/500: downloaded Singing_quail
266/500: downloaded Black-billed_brushturkey
267/500: downloaded Marail_guan
268/500: downloaded Venezuelan_wood_quail
269/500: downloaded Chestnut_wood_quail
270/500: downloaded Rufous-breasted_wood_quail
Rate limited on Rusty-margined_guan. Waiting 49 seconds.
271/500: downloaded Rusty-margined_guan
272/500: downloaded Baudo_guan
273/500: downloaded Tacarcuna_wood_quail
274/500: downloaded Blue-bearded_helmetcrest
275/500: downloaded Buffy_helmetcrest
276/500: downloaded White-bearded_helmetcrest
277/500: downloaded Tolima_blossomcrown
278/500: downloaded Rufous-gaped_hillstar
279/500: downloaded Many-spotted_hummingbird
280/500: downloaded Rivoli's_hummingbird
Rate limited on Scissor-tailed_hummingbird. Waiting 49 seconds.
281/500: downloaded Scissor-tailed_hummingbird
282/500: downloaded Violet-headed_hummingbird
283/500: downloaded Red-throated_piping_guan
284/500: downloaded Green-bearded_helmetcrest
285/500: downloaded Ferruginous_partridge
286/500: downloaded Olivaceous_thornbill
287/500: downloaded Green-tailed_emerald
288/500: downloaded Chiribiquete_emerald
289/500: downloaded Common_ostrich
290/500: downloaded Rufous-vented_whitetip
Rate limited on Western_capercaillie. Waiting 49 seconds.
291/500: downloaded Western_capercaillie
292/500: downloaded Red-tailed_comet
293/500: downloaded Black_grouse
294/500: downloaded Oasis_hummingbird
295/500: downloaded Canivet's_emerald
296/500: downloaded Blue-throated_mountaingem
297/500: downloaded Razor-billed_curassow
298/500: downloaded Green-backed_firecrown
299/500: downloaded Emerald-chinned_hummingbird
300/500: downloaded Purple-bibbed_whitetip
Rate limited on Betta_edithae. Waiting 49 seconds.
301/500: downloaded Betta_edithae
302/500: downloaded Betta_brownorum
303/500: downloaded Betta_channoides
304/500: downloaded Peaceful_betta
305/500: downloaded John_Dory
306/500: downloaded Siamese_fighting_fish
307/500: downloaded Laetacara_curviceps
308/500: downloaded Australian_grayling
309/500: downloaded Murray_cod
310/500: downloaded Nannacara_aureocephalus
Rate limited on Oscar_(fish). Waiting 49 seconds.
311/500: downloaded Oscar_(fish)
312/500: downloaded Crenicichla_punctata
313/500: downloaded Lugubria_johanna
314/500: downloaded Striped_red_mullet
315/500: downloaded Lugubria_strigata
316/500: downloaded Lugubria_tigrina
317/500: downloaded Zebra_acara
318/500: downloaded Teleocichla_cinderella
319/500: downloaded Pterophyllum_altum
320/500: downloaded Convict_cichlid
Rate limited on Australoheros_facetus. Waiting 50 seconds.
321/500: downloaded Australoheros_facetus
322/500: downloaded Blue_acara
323/500: downloaded Blue-eye_cichlid
324/500: downloaded Mesonauta_festivus
325/500: downloaded Mullus_barbatus
326/500: downloaded Goldeneye_cichlid
327/500: downloaded Green_terror
328/500: downloaded Firemouth_cichlid
329/500: downloaded Nannacara_bimaculata
330/500: downloaded Jack_Dempsey_(fish)
Rate limited on Parachromis_managuensis. Waiting 49 seconds.
331/500: downloaded Parachromis_managuensis
332/500: downloaded Rednose_labeo
333/500: downloaded Silver_labeo
334/500: downloaded Psednos_gelatinosus
335/500: downloaded Psednos_anoderkes
336/500: downloaded Psednos_harteli
337/500: downloaded Psednos_micrurus
338/500: downloaded Psednos_nataliae
339/500: downloaded Lingcod
340/500: downloaded Petenia_splendida
Rate limited on Paraliparis_labiatus. Waiting 49 seconds.
341/500: downloaded Paraliparis_labiatus
342/500: downloaded Paraliparis_eastmani
343/500: downloaded Paraliparis_delphis
344/500: downloaded Paraliparis_hobarti
345/500: downloaded Paraliparis_incognita
346/500: downloaded Paraliparis_kocki
347/500: downloaded Paraliparis_impariporus
348/500: downloaded Paraliparis_coracinus
349/500: downloaded Paraliparis_dewitti
350/500: downloaded Paraliparis_avellaneus
Rate limited on Paraliparis_brunneocaudatus. Waiting 49 seconds.
351/500: downloaded Paraliparis_brunneocaudatus
352/500: downloaded Paraliparis_costatus
353/500: downloaded Paraliparis_lasti
354/500: downloaded Paraliparis_infeliciter
355/500: downloaded Paraliparis_brunneus
356/500: downloaded Paraliparis_badius
357/500: downloaded Pseudoplatystoma_magdaleniatum
358/500: downloaded Pinirampus_pirinampu
359/500: downloaded Zungaropsis
360/500: downloaded Sorubim_lima
Rate limited on Pinguipes_brasilianus. Waiting 49 seconds.
361/500: downloaded Pinguipes_brasilianus
362/500: downloaded Trixiphichthys_weberi
363/500: downloaded Alburnoides_qanati
364/500: downloaded Redhump_eartheater
365/500: downloaded Psychrolutes_marcidus
366/500: downloaded Mahi-mahi
367/500: downloaded Stipecampus_cristatus
368/500: downloaded Synchiropus_splendidus
369/500: downloaded Paraliparis_bipolaris
370/500: downloaded Paraliparis_gomoni
Rate limited on Black_seasnail. Waiting 49 seconds.
371/500: downloaded Black_seasnail
372/500: downloaded Paraliparis_carlbondi
373/500: downloaded Pugnose_shiner
374/500: downloaded Labeo_rosae
375/500: downloaded Lemon_sole
376/500: downloaded Red_cornetfish
377/500: downloaded Pseudorhombus_arsius
378/500: downloaded Alburnoides_eichwaldii
379/500: downloaded Alburnoides_prespensis
380/500: downloaded Javichthys_kailolae
Rate limited on Transcaucasian_spirlin. Waiting 49 seconds.
381/500: downloaded Transcaucasian_spirlin
382/500: downloaded Pao_leiurus
383/500: downloaded Mazarunia_mazarunii
384/500: downloaded Satanoperca_lilith
385/500: downloaded Aplochiton_taeniatus
386/500: downloaded Aplochiton_zebra
387/500: downloaded Razorbelly_scad
388/500: downloaded European_eel
389/500: downloaded Whitetip_weasel_shark
390/500: downloaded Anarhichas_minor
Rate limited on Australian_weasel_shark. Waiting 49 seconds.
391/500: downloaded Australian_weasel_shark
392/500: downloaded Sicklefin_weasel_shark
393/500: downloaded Straight-tooth_weasel_shark
394/500: downloaded Atlantic_weasel_shark
395/500: downloaded Slender_weasel_shark
396/500: downloaded Barbeled_houndshark
397/500: downloaded European_plaice
398/500: downloaded Beaufortia_kweichowensis
399/500: downloaded Blue_shark
400/500: downloaded Omul
Rate limited on Marmorerpeton_wakei. Waiting 49 seconds.
401/500: downloaded Marmorerpeton_wakei
402/500: downloaded Boulengerula_taitana
403/500: downloaded Caecilia_volcani
404/500: downloaded Siphonops_annulatus
405/500: downloaded Stefania_roraimae
406/500: downloaded Italian_crested_newt
407/500: downloaded Danube_crested_newt
408/500: downloaded Boulengerula_niedeni
409/500: downloaded Northern_crested_newt
410/500: downloaded Two-toed_amphiuma
Rate limited on Stefania_scalae. Waiting 49 seconds.
411/500: downloaded Stefania_scalae
412/500: downloaded Stefania_marahuaquensis
413/500: downloaded Stefania_evansi
414/500: downloaded Caecilia_crassisquama
415/500: downloaded Amphiuma_pholeter
416/500: downloaded Siphonops_hardyi
417/500: downloaded Stefania_riae

In [27]:

pageviews_table = pd.concat(
    pageview_results,
    ignore_index=True
)

In [28]:
# With animal names and classes
animals_full = pageviews_table.merge(
    animals,
    on="page_title",
    how="left"
).merge(
    image_table,
    on="page_title",
    how="left"
)
animals_full.to_csv(
    output_folder / "animals_full.csv",
    index=False
)
animals_full

,page_title,date,pageviews,animal,animal_class,image_count
0,Eastern_bent-wing_bat,20250101,2,Eastern bent-wing bat,Mammal,3
1,Eastern_bent-wing_bat,20250102,0,Eastern bent-wing bat,Mammal,3
2,Eastern_bent-wing_bat,20250103,0,Eastern bent-wing bat,Mammal,3
3,Eastern_bent-wing_bat,20250104,0,Eastern bent-wing bat,Mammal,3
4,Eastern_bent-wing_bat,20250105,3,Eastern bent-wing bat,Mammal,3
...,...,...,...,...,...,...
166509,Leptobrachella_aerea,20251227,2,Leptobrachella aerea,Amphibian,2
166510,Leptobrachella_aerea,20251228,1,Leptobrachella aerea,Amphibian,2
166511,Leptobrachella_aerea,20251229,2,Leptobrachella aerea,Amphibian,2
166512,Leptobrachella_aerea,20251230,2,Leptobrachella aerea,Amphibian,2
166513,Leptobrachella_aerea,20251231,1,Leptobrachella aerea,Amphibian,2